server:
  port: 8100
spring: 
  application: 
    name: dxg-eureka
  #开启注册中心登录认证
  basic: 
    enable: true    
  security: 
    user: 
      name: root
      password: 123456	   
#注册中心url
eureka: 
  instance: 
    hostname: localhost
  client: 
    service-url: 
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8000/eureka/
     #注册中心发现为false，多个时为true
    register-with-eureka: false
    fetch-registry: false
  server: 
    enable-self-preservation: false 	#关闭自我保护
    eviction-interval-timer-in-seconds: 5  	#清理服务列表间隔/秒

     
