server:
   port: 8001
   servlet:
     context-path: /dxg-admin
spring:
   datasource:
     username: root
     password: 123456
     url: jdbc:mysql://192.168.33.130:3306/dxg?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
   redis:
     database: 0
     host: 192.168.33.130
     port: 6379
     timeout: 1000
     #password:
     pool:
       minIdle: 1		# 连接池中的最小空闲连接  
       maxIdle: 10		# 连接池中的最大空闲连接
       maxWait: 3		# 连接池最大阻塞等待时间（使用负值表示没有限制）  
       maxActive: 8 	# 连接池最大连接数（使用负值表示没有限制）  
 
     
