server:
   port: 8105
   servlet:
     context-path: /dxg-admin
spring:
   application:
     name: dxg-admin
   datasource:
     username: root
     password: 123456
     url: jdbc:mysql://106.52.60.213:3306/dxg?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.cj.jdbc.Driver
   redis:
     database: 1
     host: 106.52.60.213
     port: 6379
     timeout: 1000
     #password:
     pool:
       minIdle: 1		# 连接池中的最小空闲连接  
       maxIdle: 10		# 连接池中的最大空闲连接
       maxWait: 3		# 连接池最大阻塞等待时间（使用负值表示没有限制）  
       maxActive: 8 	# 连接池最大连接数（使用负值表示没有限制）  
       
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8100/eureka
    register-with-eureka: true
    fetch-registry: true
    
  instance: #eureka客户端实例配置
    lease-renewal-interval-in-seconds: 5 #定义服务多久去注册中心续约
    lease-expiration-duration-in-seconds: 5 #定义服务多久不去续约认为服务失效
     
